version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
    networks:
      - todo-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://3.144.150.117:3000  
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    

    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge

